/* This code is generated by express-generator ,

you can require your own files but dont remove anything

By Nidhi Mittal and Aniket Batabyal
*/
var createError = require('http-errors');
var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');
var bodyParser = require('body-parser');


/* this is the area where routes are made

  can be edited by devolopers

*/
var indexRouter = require('./routes/index');
var addResume = require('./routes/addResume');


/* end of routing part */

var app = express();

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs'); // this is so that the express can search for ejs files

app.use(logger('dev')); // generated by express-generator
app.use(express.json()); // generated by express generator
app.use(express.urlencoded({ extended: false }));// generated by express-generator
app.use(cookieParser());// generated by express-generator
app.use(express.static(path.join(__dirname, 'public')));// generated by express-generator so that it reads css and js static folders
app.use(bodyParser.urlencoded({extended : true})); // generated by anarchymonkey

/* ROUTES FOR THE WHOLE APPP */
app.use('/', indexRouter);
app.use('/add', addResume);
/* END OF ROUTES */

/* This is generated by express-generator , not to be touched */


// catch 404 and forward to error handler
app.use(function(req, res, next) {
  next(createError(404));
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

module.exports = app;
/* this is the end of the generated code */
